= Yazılım Tasarım Kalıpları

== Batuhan Subaşı - 160202091

=== 1.Hafta - Tamamlandı √

- Wiki, projects, issues sekmeleri aktif olarak kullanıldı. (1.Hafta klasörü ve diğer github sekmeleri)

=== 2.Hafta - Tamamlandı √

- UML Diyagramı ascidocc formatında görsel görüntüsü ile beraber eklendi. (UML_Class_diagram klasörü)

- Bu ödevin teslimi Commit: 39588d7 commiti ile gününde teslim edildi. Sonrasında UML yapısında değişiklik yapıldı.

=== 3.Hafta - Tamamlandı √

- Singleton Pattern ve Factory Pattern yaklaşımları 2 ayrı klasör ile eklendi. (Thread_Safe_Singleton ve Factory_Pattern klasörleri)
- Klasör İçeriği: UML Görüntüsü, UML Kodu, Pattern Kodu.

=== 4.Hafta - Tamamlandı √

- Prototype -> YazilimTasarimKaliplari -> Program.cs - Hem shallow copy hem de deep copy metoduyla nesneler kopyalandı.
- Prototype -> ShallowandDeepCopy.adoc - Kodun dokümantasyonu ascidoc formatında yapıldı.
- Prototype -> UMLPrototype.adoc -> UML Diyagramının kodu paylaşıldı.
- Prototype -> UMLPrototype.png -> UML Diyagramının ekran görüntüsü paylaşıldı.
- ObjectPool -> YazilimTasarimKaliplari -> Java dilinde proje dizini paylasildi.
- ObjectPool -> ObjectPool.adoc - Kodun dokümantasyonu ascidoc formatında yapıldı.
- ObjectPool -> UMLObjectPool.adoc -> UML Diyagramının kodu paylaşıldı.
- ObjectPool -> UMLObjectPool.png -> UML Diyagramının ekran görüntüsü paylaşıldı.

=== 5.Hafta - Devam edecek 
